//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AthleteAddaProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public int Publisher_Id { get; set; }
        public string Publisher_Name { get; set; }
        public string Email_Id { get; set; }
        public string Mobile_No { get; set; }
        public string Display_Name { get; set; }
        public string Display_Picture { get; set; }
    }
}
